"""Big 'channel:CB_JIGSAW' reservoir, uniform conditioning + azimuth gradient.

Auto-generated by ../setup_uniform.py.  Every block in the 10x10 grid
receives the same scalars (set to the per-type training-data MEDIAN); the
azimuth varies linearly from 70 deg to 120 deg along X.  No Y variation.

Raw scalars used (training median for layer 'channel:CB_JIGSAW'):
    ntg                    0.385
    width_cells            10.72
    depth_cells            6.5
    mCHsinu                1.25
    mFFCHprop              0.4
    probAvulInside         0.375
"""
import os
import time

import numpy as np
import torch

from genflows.models.unet3d import UNet3D
from genflows.methods.flow_matching import FlowMatching
from genflows.assembly import (
    BlockSpec, COND_DIM, LAYER_TYPE_TO_IDX,
    generate_big_reservoir_multi,
)


CKPT = os.path.join(os.environ.get('SCRATCH', '.'), 'genflows_runs/reservoirs_inpainting/checkpoints/flow_matching.pt')
COND_STATS = os.path.join(os.environ.get('SCRATCH', '.'), 'genflows_runs/reservoirs_inpainting/checkpoints/cond_stats.npz')
OUT_DIR = os.environ.get('RESERVOIR_OUT_DIR', 'results')

GRID_SHAPE = (10, 10)
BLOCK_SHAPE = (64, 64, 32)
OVERLAPS = [12, 16, 24]
SEED = 42
N_STEPS = 50
CFG_SCALE = 3.0

LAYER_TYPE_NAME = 'channel:CB_JIGSAW'
RAW_SCALARS = {'ntg': 0.385, 'width_cells': 10.72, 'depth_cells': 6.5, 'mCHsinu': 1.25, 'mFFCHprop': 0.4, 'probAvulInside': 0.375}
AZIMUTH_DEG_RANGE = (70.0, 120.0)


def build_grid_specs(cont_min, cont_max):
    """Uniform scalars per block, azimuth gradient along X (no Y change)."""
    ny, nx = GRID_SHAPE
    grid = []
    for _ in range(ny):
        row = []
        for j in range(nx):
            fx = j / max(nx - 1, 1)
            az = AZIMUTH_DEG_RANGE[0] + fx * (
                AZIMUTH_DEG_RANGE[1] - AZIMUTH_DEG_RANGE[0])
            row.append(BlockSpec(
                layer_idx=LAYER_TYPE_TO_IDX[LAYER_TYPE_NAME],
                azimuth_deg=az,
                raw_scalars=dict(RAW_SCALARS),
            ))
        grid.append(row)
    return grid


def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"Device: {device}  out: {OUT_DIR}")
    print(f"Grid: {GRID_SHAPE[0]}x{GRID_SHAPE[1]} blocks of {BLOCK_SHAPE}")
    print(f"Layer type: {LAYER_TYPE_NAME}")
    print(f"Uniform raw scalars: {RAW_SCALARS}")
    print(f"Azimuth gradient X: {AZIMUTH_DEG_RANGE[0]} -> {AZIMUTH_DEG_RANGE[1]}")

    stats = np.load(COND_STATS, allow_pickle=True)
    cont_min, cont_max = stats['cont_min'], stats['cont_max']

    grid = build_grid_specs(cont_min, cont_max)

    model = UNet3D(in_channels=3, out_channels=1, num_cond=COND_DIM,
                   num_time_embs=1, expand_angle_idx=None).to(device)
    model.load_state_dict(torch.load(CKPT, map_location=device, weights_only=True))
    model.eval()
    method = FlowMatching(model)

    ny, nx = GRID_SHAPE
    Sx, Sy, Sz = BLOCK_SHAPE

    for overlap in OVERLAPS:
        tag = f"hard_ov{overlap:02d}"
        Tx = Sx + (nx - 1) * (Sx - overlap)
        Ty = Sy + (ny - 1) * (Sy - overlap)
        print(f"\n== {tag} == grid={ny}x{nx}, total={Tx}x{Ty}x{Sz}")
        torch.manual_seed(SEED)
        t0 = time.time()
        x_global, _ = generate_big_reservoir_multi(
            method, grid, cont_min, cont_max,
            block_shape=BLOCK_SHAPE, overlap_xy=overlap,
            n_steps=N_STEPS, cfg_scale=CFG_SCALE,
            max_batch=24, device=device,
        )
        elapsed = time.time() - t0
        volume = x_global.numpy()
        binary = (volume > 0).astype(np.int8)

        out_npz = os.path.join(OUT_DIR, f"reservoir_{tag}.npz")
        np.savez(out_npz,
                 volume=volume.astype(np.float32),
                 binary=binary,
                 mode='hard',
                 overlap=overlap,
                 block_shape=np.array(BLOCK_SHAPE),
                 ny=ny, nx=nx,
                 pure_x_indices=np.array(list(range(nx)), dtype=np.int32),
                 pure_x_layer=np.array([LAYER_TYPE_NAME] * nx, dtype=object),
                 trans_x_indices=np.array([], dtype=np.int32),
                 trans_kind='hard',
                 row_azimuths_deg=np.array(
                     [grid[i][nx // 2].azimuth_deg for i in range(ny)],
                     dtype=np.float32),
                 elapsed_s=elapsed)
        print(f"  saved -> {out_npz}")
        print(f"  shape={binary.shape}  NTG={binary.mean():.3f}  "
              f"{elapsed:.1f}s")


if __name__ == '__main__':
    main()
