"""Create per-type subdirs (visualize.py + wells_entropy.py copied from
lobes/, generate.py templated with per-type scalars) for all channel
families.  Run from this directory:

    python setup_other_types.py

After this, each subdir is self-contained and can be driven the same way as
lobes/:
    cd <type>/ ; python generate.py && python visualize.py && \\
        python wells_entropy.py --overlap 16 --n-real 50
"""
import os
import shutil
import textwrap


HERE = os.path.dirname(os.path.abspath(__file__))
LOBES_DIR = os.path.join(HERE, 'lobes')


# ---------------------------------------------------------------------------
# Per-type scalar choices.  All values are *normalized fractions* of the
# global training range (cont_min..cont_max), kept inside the middle 60% of
# the range so we stay well within the training distribution and don't get
# salt-and-pepper degeneration.  Numbers reflect rough geological intuition
# for each family; these are starting points and easy to tweak per subdir.
#
# width / depth / mCHsinu vary with Y (bottom is the larger value, top the
# smaller — same convention as lobes/).  azimuth varies with X.  All other
# family scalars are fixed per type.
# ---------------------------------------------------------------------------

TYPE_CONFIGS = {
    'pv_shoestring': {
        'layer_type': 'channel:PV_SHOESTRING',
        'ntg':              0.35,
        'width_norm_range': (0.30, 0.10),   # raw ~25 -> ~10
        'depth_norm_range': (0.50, 0.20),   # raw ~11 -> ~6
        'mchsinu_norm':     (0.30, 0.05),   # low sinuosity (straight ribbons)
        'mffchprop_fixed':  0.00,
        'probavul_fixed':   0.00,
    },
    'meander_oxbow': {
        'layer_type': 'channel:MEANDER_OXBOW',
        'ntg':              0.50,
        'width_norm_range': (0.35, 0.15),
        'depth_norm_range': (0.50, 0.25),
        'mchsinu_norm':     (0.95, 0.55),   # high sinuosity (meanders + oxbows)
        'mffchprop_fixed':  0.10,
        'probavul_fixed':   0.00,
    },
    'cb_jigsaw': {
        'layer_type': 'channel:CB_JIGSAW',
        'ntg':              0.55,
        'width_norm_range': (0.45, 0.20),
        'depth_norm_range': (0.50, 0.25),
        'mchsinu_norm':     (0.55, 0.30),
        'mffchprop_fixed':  0.10,
        'probavul_fixed':   0.30,
    },
    'cb_labyrinth': {
        'layer_type': 'channel:CB_LABYRINTH',
        'ntg':              0.55,
        'width_norm_range': (0.45, 0.20),
        'depth_norm_range': (0.50, 0.25),
        'mchsinu_norm':     (0.55, 0.30),
        'mffchprop_fixed':  0.10,
        'probavul_fixed':   0.40,
    },
    'sh_distal': {
        'layer_type': 'channel:SH_DISTAL',
        'ntg':              0.35,
        'width_norm_range': (0.50, 0.25),
        'depth_norm_range': (0.45, 0.20),
        'mchsinu_norm':     (0.40, 0.20),
        'mffchprop_fixed':  0.15,
        'probavul_fixed':   0.20,
    },
    'sh_proximal': {
        'layer_type': 'channel:SH_PROXIMAL',
        'ntg':              0.65,
        'width_norm_range': (0.50, 0.25),
        'depth_norm_range': (0.45, 0.20),
        'mchsinu_norm':     (0.40, 0.20),
        'mffchprop_fixed':  0.10,
        'probavul_fixed':   0.20,
    },
}


GENERATE_TEMPLATE = '''"""Big {layer_type!r} reservoir with varying channel properties across the grid.

Auto-generated by ../setup_other_types.py from a per-type config.  Mirrors
the lobes/big_reservoir gradient pattern: width / depth / mCHsinu vary
along Y, azimuth along X, NTG fixed.
"""
import os
import time

import numpy as np
import torch

from resflow.models.unet3d import UNet3D
from resflow.methods.flow_matching import FlowMatching
from resflow.assembly import (
    BlockSpec, COND_DIM, LAYER_TYPE_TO_IDX,
    generate_big_reservoir_multi,
)


CKPT = os.path.join(os.environ.get('SCRATCH', '.'), 'genflows_runs/reservoirs_inpainting/checkpoints/flow_matching.pt')
COND_STATS = os.path.join(os.environ.get('SCRATCH', '.'), 'genflows_runs/reservoirs_inpainting/checkpoints/cond_stats.npz')
OUT_DIR = os.environ.get('RESERVOIR_OUT_DIR', 'results')

GRID_SHAPE = (10, 10)
BLOCK_SHAPE = (64, 64, 32)
OVERLAPS = [12, 16, 24]
SEED = 42
N_STEPS = 50
CFG_SCALE = 3.0

LAYER_TYPE_NAME = {layer_type!r}
NTG_FIXED = {ntg}
WIDTH_NORM_RANGE   = {width_norm_range}
DEPTH_NORM_RANGE   = {depth_norm_range}
MCHSINU_NORM_RANGE = {mchsinu_norm}
MFFCHPROP_FIXED    = {mffchprop_fixed}
PROBAVUL_FIXED     = {probavul_fixed}
AZIMUTH_DEG_RANGE  = (20.0, 160.0)


def _denorm(norm, lo, hi):
    return float(lo + norm * (hi - lo))


def build_grid_specs(cont_min, cont_max):
    """Build (ny, nx) BlockSpec grid: same layer type everywhere, scalars
    from the per-axis gradients defined above."""
    ny, nx = GRID_SHAPE
    # CONT_COLS = ['ntg','width_cells','depth_cells','asp','mCHsinu',
    #              'mFFCHprop','probAvulInside','trunk_length_fraction']
    w_lo, w_hi = cont_min[1], cont_max[1]
    d_lo, d_hi = cont_min[2], cont_max[2]
    s_lo, s_hi = cont_min[4], cont_max[4]   # mCHsinu

    grid = []
    for i in range(ny):
        fy = i / max(ny - 1, 1)
        wn = WIDTH_NORM_RANGE[0]   + fy * (WIDTH_NORM_RANGE[1]   - WIDTH_NORM_RANGE[0])
        dn = DEPTH_NORM_RANGE[0]   + fy * (DEPTH_NORM_RANGE[1]   - DEPTH_NORM_RANGE[0])
        mn = MCHSINU_NORM_RANGE[0] + fy * (MCHSINU_NORM_RANGE[1] - MCHSINU_NORM_RANGE[0])
        width = _denorm(wn, w_lo, w_hi)
        depth = _denorm(dn, d_lo, d_hi)
        msinu = _denorm(mn, s_lo, s_hi)
        row = []
        for j in range(nx):
            fx = j / max(nx - 1, 1)
            az = AZIMUTH_DEG_RANGE[0] + fx * (AZIMUTH_DEG_RANGE[1] - AZIMUTH_DEG_RANGE[0])
            row.append(BlockSpec(
                layer_idx=LAYER_TYPE_TO_IDX[LAYER_TYPE_NAME],
                azimuth_deg=az,
                raw_scalars={{
                    'ntg': NTG_FIXED,
                    'width_cells': width,
                    'depth_cells': depth,
                    'mCHsinu': msinu,
                    'mFFCHprop': MFFCHPROP_FIXED,
                    'probAvulInside': PROBAVUL_FIXED,
                }},
            ))
        grid.append(row)
    return grid


def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"Device: {{device}}  out: {{OUT_DIR}}")
    print(f"Grid: {{GRID_SHAPE[0]}}x{{GRID_SHAPE[1]}} blocks of {{BLOCK_SHAPE}}")
    print(f"Layer type: {{LAYER_TYPE_NAME}}")

    stats = np.load(COND_STATS, allow_pickle=True)
    cont_min, cont_max = stats['cont_min'], stats['cont_max']

    grid = build_grid_specs(cont_min, cont_max)
    print(f"\\nProperty gradient (NTG={{NTG_FIXED}} fixed):")
    print(f"  width_cells  Y: {{grid[0][0].raw_scalars['width_cells']:6.1f}}  "
          f"-> {{grid[-1][0].raw_scalars['width_cells']:6.1f}}")
    print(f"  depth_cells  Y: {{grid[0][0].raw_scalars['depth_cells']:6.1f}}  "
          f"-> {{grid[-1][0].raw_scalars['depth_cells']:6.1f}}")
    print(f"  mCHsinu      Y: {{grid[0][0].raw_scalars['mCHsinu']:6.2f}}  "
          f"-> {{grid[-1][0].raw_scalars['mCHsinu']:6.2f}}")
    print(f"  mFFCHprop  fixed: {{MFFCHPROP_FIXED}}")
    print(f"  probAvul   fixed: {{PROBAVUL_FIXED}}")
    print(f"  azimuth      X: {{grid[0][0].azimuth_deg:6.1f}}  "
          f"-> {{grid[0][-1].azimuth_deg:6.1f}}")

    model = UNet3D(in_channels=3, out_channels=1, num_cond=COND_DIM,
                   num_time_embs=1, expand_angle_idx=None).to(device)
    model.load_state_dict(torch.load(CKPT, map_location=device, weights_only=True))
    model.eval()
    method = FlowMatching(model)

    ny, nx = GRID_SHAPE
    Sx, Sy, Sz = BLOCK_SHAPE

    for overlap in OVERLAPS:
        tag = f"hard_ov{{overlap:02d}}"
        Tx = Sx + (nx - 1) * (Sx - overlap)
        Ty = Sy + (ny - 1) * (Sy - overlap)
        print(f"\\n== {{tag}} == grid={{ny}}x{{nx}}, total={{Tx}}x{{Ty}}x{{Sz}}")
        torch.manual_seed(SEED)
        t0 = time.time()
        x_global, _ = generate_big_reservoir_multi(
            method, grid, cont_min, cont_max,
            block_shape=BLOCK_SHAPE, overlap_xy=overlap,
            n_steps=N_STEPS, cfg_scale=CFG_SCALE,
            max_batch=24, device=device,
        )
        elapsed = time.time() - t0
        volume = x_global.numpy()
        binary = (volume > 0).astype(np.int8)

        out_npz = os.path.join(OUT_DIR, f"reservoir_{{tag}}.npz")
        np.savez(out_npz,
                 volume=volume.astype(np.float32),
                 binary=binary,
                 mode='hard',
                 overlap=overlap,
                 block_shape=np.array(BLOCK_SHAPE),
                 ny=ny, nx=nx,
                 pure_x_indices=np.array(list(range(nx)), dtype=np.int32),
                 pure_x_layer=np.array([LAYER_TYPE_NAME] * nx, dtype=object),
                 trans_x_indices=np.array([], dtype=np.int32),
                 trans_kind='hard',
                 row_azimuths_deg=np.array(
                     [grid[i][0].azimuth_deg for i in range(ny)],
                     dtype=np.float32),
                 elapsed_s=elapsed)
        print(f"  saved -> {{out_npz}}")
        print(f"  shape={{binary.shape}}  NTG={{binary.mean():.3f}}  "
              f"{{elapsed:.1f}}s")


if __name__ == '__main__':
    main()
'''


def main():
    for name, cfg in TYPE_CONFIGS.items():
        subdir = os.path.join(HERE, name)
        os.makedirs(subdir, exist_ok=True)
        # Copy the (already-vectorised, well-overlay-aware) viz + entropy.
        shutil.copy(os.path.join(LOBES_DIR, 'visualize.py'),
                    os.path.join(subdir, 'visualize.py'))
        shutil.copy(os.path.join(LOBES_DIR, 'wells_entropy.py'),
                    os.path.join(subdir, 'wells_entropy.py'))
        # Render the templated generate.py.
        with open(os.path.join(subdir, 'generate.py'), 'w') as f:
            f.write(GENERATE_TEMPLATE.format(**cfg))
        print(f"  wrote {subdir}/{{generate.py,visualize.py,wells_entropy.py}}")
    print(f"\nDone — created {len(TYPE_CONFIGS)} subdirs.")


if __name__ == '__main__':
    main()
