"""Per-type uniform big-reservoir generators.

For every reservoir family (excluding delta) regenerate the subdir's
generate.py with:
  - uniform raw scalars set to the per-type training-data MEDIAN
  - azimuth varying linearly from 70 deg to 120 deg along X
  - identical scalars in every Y row

Sources for the medians: SiliciclasticReservoirs train split via the
_cond_cache built by data_reservoirs.py.  Computed once at the top of
this file.

Run from this directory:
    python setup_uniform.py
This (re)writes ``<type>/generate.py`` and copies ``<type>/visualize.py``
from lobes/ so every subdir has the latest plotters.
"""
import os
import shutil


HERE = os.path.dirname(os.path.abspath(__file__))
LOBES_DIR = os.path.join(HERE, 'lobes')


# Training-data median per type for every column the model conditions on.
# Family-only columns (asp / mCHsinu / mFFCHprop / probAvulInside) are
# omitted from raw_scalars when the family doesn't use them.
TYPE_CONFIGS = {
    # NOTE: 'lobes' is intentionally excluded — it has its own gradient
    # generate.py (varying width/depth/asp along Y, azimuth along X).
    # Don't overwrite that.
    'pv_shoestring': {
        'layer_type': 'channel:PV_SHOESTRING',
        'raw_scalars': {
            'ntg':            0.226,
            'width_cells':    6.97,
            'depth_cells':    6.50,
            'mCHsinu':        1.575,
            'mFFCHprop':      0.150,
            'probAvulInside': 0.060,
        },
    },
    'meander_oxbow': {
        'layer_type': 'channel:MEANDER_OXBOW',
        'raw_scalars': {
            'ntg':            0.415,
            'width_cells':    6.97,
            'depth_cells':    6.50,
            'mCHsinu':        1.625,
            'mFFCHprop':      0.000,
            'probAvulInside': 0.000,
        },
    },
    'cb_jigsaw': {
        'layer_type': 'channel:CB_JIGSAW',
        'raw_scalars': {
            'ntg':            0.385,
            'width_cells':    10.72,
            'depth_cells':    6.50,
            'mCHsinu':        1.250,
            'mFFCHprop':      0.400,
            'probAvulInside': 0.375,
        },
    },
    'cb_labyrinth': {
        'layer_type': 'channel:CB_LABYRINTH',
        'raw_scalars': {
            'ntg':            0.372,
            'width_cells':    10.18,
            'depth_cells':    6.50,
            'mCHsinu':        1.275,
            'mFFCHprop':      0.325,
            'probAvulInside': 0.060,
        },
    },
    'sh_distal': {
        'layer_type': 'channel:SH_DISTAL',
        'raw_scalars': {
            'ntg':            0.620,
            'width_cells':    11.51,
            'depth_cells':    6.50,
            'mCHsinu':        1.275,
            'mFFCHprop':      0.100,
            'probAvulInside': 0.060,
        },
    },
    'sh_proximal': {
        'layer_type': 'channel:SH_PROXIMAL',
        'raw_scalars': {
            'ntg':            0.509,
            'width_cells':    13.39,
            'depth_cells':    6.50,
            'mCHsinu':        1.225,
            'mFFCHprop':      0.225,
            'probAvulInside': 0.350,
        },
    },
}


GENERATE_TEMPLATE = '''"""Big {layer_type!r} reservoir, uniform conditioning + azimuth gradient.

Auto-generated by ../setup_uniform.py.  Every block in the 10x10 grid
receives the same scalars (set to the per-type training-data MEDIAN); the
azimuth varies linearly from 70 deg to 120 deg along X.  No Y variation.

Raw scalars used (training median for layer {layer_type!r}):
{scalar_doc}
"""
import os
import time

import numpy as np
import torch

from resflow.models.unet3d import UNet3D
from resflow.methods.flow_matching import FlowMatching
from resflow.assembly import (
    BlockSpec, COND_DIM, LAYER_TYPE_TO_IDX,
    generate_big_reservoir_multi,
)


CKPT = os.path.join(os.environ.get('SCRATCH', '.'), 'genflows_runs/reservoirs_inpainting/checkpoints/flow_matching.pt')
COND_STATS = os.path.join(os.environ.get('SCRATCH', '.'), 'genflows_runs/reservoirs_inpainting/checkpoints/cond_stats.npz')
OUT_DIR = os.environ.get('RESERVOIR_OUT_DIR', 'results')

GRID_SHAPE = (10, 10)
BLOCK_SHAPE = (64, 64, 32)
OVERLAPS = [12, 16, 24]
SEED = 42
N_STEPS = 50
CFG_SCALE = 3.0

LAYER_TYPE_NAME = {layer_type!r}
RAW_SCALARS = {raw_scalars!r}
AZIMUTH_DEG_RANGE = (70.0, 120.0)


def build_grid_specs(cont_min, cont_max):
    """Uniform scalars per block, azimuth gradient along X (no Y change)."""
    ny, nx = GRID_SHAPE
    grid = []
    for _ in range(ny):
        row = []
        for j in range(nx):
            fx = j / max(nx - 1, 1)
            az = AZIMUTH_DEG_RANGE[0] + fx * (
                AZIMUTH_DEG_RANGE[1] - AZIMUTH_DEG_RANGE[0])
            row.append(BlockSpec(
                layer_idx=LAYER_TYPE_TO_IDX[LAYER_TYPE_NAME],
                azimuth_deg=az,
                raw_scalars=dict(RAW_SCALARS),
            ))
        grid.append(row)
    return grid


def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"Device: {{device}}  out: {{OUT_DIR}}")
    print(f"Grid: {{GRID_SHAPE[0]}}x{{GRID_SHAPE[1]}} blocks of {{BLOCK_SHAPE}}")
    print(f"Layer type: {{LAYER_TYPE_NAME}}")
    print(f"Uniform raw scalars: {{RAW_SCALARS}}")
    print(f"Azimuth gradient X: {{AZIMUTH_DEG_RANGE[0]}} -> {{AZIMUTH_DEG_RANGE[1]}}")

    stats = np.load(COND_STATS, allow_pickle=True)
    cont_min, cont_max = stats['cont_min'], stats['cont_max']

    grid = build_grid_specs(cont_min, cont_max)

    model = UNet3D(in_channels=3, out_channels=1, num_cond=COND_DIM,
                   num_time_embs=1, expand_angle_idx=None).to(device)
    model.load_state_dict(torch.load(CKPT, map_location=device, weights_only=True))
    model.eval()
    method = FlowMatching(model)

    ny, nx = GRID_SHAPE
    Sx, Sy, Sz = BLOCK_SHAPE

    for overlap in OVERLAPS:
        tag = f"hard_ov{{overlap:02d}}"
        Tx = Sx + (nx - 1) * (Sx - overlap)
        Ty = Sy + (ny - 1) * (Sy - overlap)
        print(f"\\n== {{tag}} == grid={{ny}}x{{nx}}, total={{Tx}}x{{Ty}}x{{Sz}}")
        torch.manual_seed(SEED)
        t0 = time.time()
        x_global, _ = generate_big_reservoir_multi(
            method, grid, cont_min, cont_max,
            block_shape=BLOCK_SHAPE, overlap_xy=overlap,
            n_steps=N_STEPS, cfg_scale=CFG_SCALE,
            max_batch=24, device=device,
        )
        elapsed = time.time() - t0
        volume = x_global.numpy()
        binary = (volume > 0).astype(np.int8)

        out_npz = os.path.join(OUT_DIR, f"reservoir_{{tag}}.npz")
        np.savez(out_npz,
                 volume=volume.astype(np.float32),
                 binary=binary,
                 mode='hard',
                 overlap=overlap,
                 block_shape=np.array(BLOCK_SHAPE),
                 ny=ny, nx=nx,
                 pure_x_indices=np.array(list(range(nx)), dtype=np.int32),
                 pure_x_layer=np.array([LAYER_TYPE_NAME] * nx, dtype=object),
                 trans_x_indices=np.array([], dtype=np.int32),
                 trans_kind='hard',
                 row_azimuths_deg=np.array(
                     [grid[i][nx // 2].azimuth_deg for i in range(ny)],
                     dtype=np.float32),
                 elapsed_s=elapsed)
        print(f"  saved -> {{out_npz}}")
        print(f"  shape={{binary.shape}}  NTG={{binary.mean():.3f}}  "
              f"{{elapsed:.1f}}s")


if __name__ == '__main__':
    main()
'''


def _scalar_doc(d):
    return '\n'.join(f'    {k:<22} {v}' for k, v in d.items())


def main():
    for sub, cfg in TYPE_CONFIGS.items():
        subdir = os.path.join(HERE, sub)
        os.makedirs(subdir, exist_ok=True)
        # Always copy the latest visualize.py (skip when subdir == LOBES_DIR).
        if os.path.abspath(subdir) != os.path.abspath(LOBES_DIR):
            shutil.copy(os.path.join(LOBES_DIR, 'visualize.py'),
                        os.path.join(subdir, 'visualize.py'))
        with open(os.path.join(subdir, 'generate.py'), 'w') as f:
            f.write(GENERATE_TEMPLATE.format(
                layer_type=cfg['layer_type'],
                raw_scalars=cfg['raw_scalars'],
                scalar_doc=_scalar_doc(cfg['raw_scalars']),
            ))
        print(f"  wrote {subdir}/generate.py + visualize.py")
    print(f"\nDone — updated {len(TYPE_CONFIGS)} subdirs.")


if __name__ == '__main__':
    main()
