import torch
import torch.nn.functional as F
from torch.utils.data import TensorDataset

from .flow_matching import FlowMatching


class RectifiedFlow(FlowMatching):
    """Rectified Flow (Liu et al., "Flow Straight and Fast").

    Round 1 = standard Flow Matching (independent noise).
    Round 2+ = reflow: train on coupled (noise, data) pairs generated by
    ODE integration of the previous round's model, producing straighter paths.
    """

    def compute_loss(self, x1, labels, x0=None):
        if x0 is None:
            x0 = torch.randn_like(x1)

        t = torch.rand((x1.shape[0],), device=x1.device)
        t_expand = t[:, None, None, None]
        xt = (1 - t_expand) * x0 + t_expand * x1

        v_target = x1 - x0

        # Randomly drop labels for classifier-free guidance training
        drop_mask = torch.rand(x1.shape[0], device=x1.device) < self.drop_prob
        labels = labels.clone()
        labels[drop_mask] = self.num_classes

        v_pred = self.model(xt, t, labels)
        return F.mse_loss(v_pred, v_target)

    @torch.no_grad()
    def generate_reflow_pairs(self, dataloader, device, n_steps=100):
        """Generate coupled (noise, generated_data, label) pairs via forward ODE.

        For each training sample x1, sample noise x0, then integrate the ODE
        from x0 (t=0) to t=1 to produce x1_generated. The pair (x0, x1_generated)
        forms a coupled dataset for the next reflow round.
        Noise marginal is exact; data marginal is approximate.
        """
        self.model.eval()

        all_x0 = []
        all_x1 = []
        all_labels = []

        for x1, labels in dataloader:
            x1 = x1.to(device)
            labels = labels.to(device)
            batch_size = x1.shape[0]

            x0 = torch.randn_like(x1)

            # Integrate ODE from t=0 to t=1 using Euler method
            x = x0.clone()
            dt = 1.0 / n_steps
            for i in range(n_steps):
                t = torch.full((batch_size,), i * dt, device=device)
                v_pred = self.model(x, t, labels)
                x = x + v_pred * dt

            all_x0.append(x0.cpu())
            all_x1.append(x.cpu())
            all_labels.append(labels.cpu())

        self.model.train()

        return TensorDataset(
            torch.cat(all_x0),
            torch.cat(all_x1),
            torch.cat(all_labels),
        )

    @torch.no_grad()
    def generate_reflow_pairs_backward(self, dataloader, device, n_steps=100):
        """Generate coupled (generated_noise, data, label) pairs via backward ODE.

        For each training sample x1, integrate the ODE backward from x1 (t=1)
        to t=0 to produce x0_generated. The pair (x0_generated, x1) forms a
        coupled dataset where the data marginal is exact and the noise marginal
        is approximate.
        """
        self.model.eval()

        all_x0 = []
        all_x1 = []
        all_labels = []

        for x1, labels in dataloader:
            x1 = x1.to(device)
            labels = labels.to(device)
            batch_size = x1.shape[0]

            # Integrate ODE from t=1 to t=0 (backward)
            x = x1.clone()
            dt = 1.0 / n_steps
            for i in range(n_steps):
                t = torch.full((batch_size,), 1.0 - i * dt, device=device)
                v_pred = self.model(x, t, labels)
                x = x - v_pred * dt

            all_x0.append(x.cpu())
            all_x1.append(x1.cpu())
            all_labels.append(labels.cpu())

        self.model.train()

        return TensorDataset(
            torch.cat(all_x0),
            torch.cat(all_x1),
            torch.cat(all_labels),
        )
